/**
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PaginatedListKeywordCount'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PaginatedListKeywordCount'));
  } else {
    // Browser globals (root is window)
    if (!root.CatalogueApi) {
      root.CatalogueApi = {};
    }
    root.CatalogueApi.KeywordSearchHistoryApi = factory(root.CatalogueApi.ApiClient, root.CatalogueApi.PaginatedListKeywordCount);
  }
}(this, function(ApiClient, PaginatedListKeywordCount) {
  'use strict';

  /**
   * KeywordSearchHistory service.
   * @module api/KeywordSearchHistoryApi
   * @version 1.0.0-private-beta
   */

  /**
   * Constructs a new KeywordSearchHistoryApi. 
   * @alias module:api/KeywordSearchHistoryApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Get keywords and how many times they occurred in a specified UTC date range
     * @param {Object} opts Optional parameters
     * @param {Date} opts.startDate start of UTC date range eg 1965-05-15              Defaults to 10 years ago
     * @param {Date} opts.endDate end of UTC date range eg 2006-02-20              Defaults to 10 years from now
     * @param {Number} opts.pageIndex 1-based index of page to return.  Defaults to 1
     * @param {Number} opts.pageSize number of items per page.  Defaults to 20
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaginatedListKeywordCount} and HTTP response
     */
    this.apiPorcelainKeywordSearchHistoryGetWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'startDate': opts['startDate'],
        'endDate': opts['endDate'],
        'pageIndex': opts['pageIndex'],
        'pageSize': opts['pageSize'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basic', 'oauth2'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = PaginatedListKeywordCount;

      return this.apiClient.callApi(
        '/api/porcelain/KeywordSearchHistory', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get keywords and how many times they occurred in a specified UTC date range
     * @param {Object} opts Optional parameters
     * @param {Date} opts.startDate start of UTC date range eg 1965-05-15              Defaults to 10 years ago
     * @param {Date} opts.endDate end of UTC date range eg 2006-02-20              Defaults to 10 years from now
     * @param {Number} opts.pageIndex 1-based index of page to return.  Defaults to 1
     * @param {Number} opts.pageSize number of items per page.  Defaults to 20
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaginatedListKeywordCount}
     */
    this.apiPorcelainKeywordSearchHistoryGet = function(opts) {
      return this.apiPorcelainKeywordSearchHistoryGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
