/**
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Organisations'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Organisations'));
  } else {
    // Browser globals (root is window)
    if (!root.CatalogueApi) {
      root.CatalogueApi = {};
    }
    root.CatalogueApi.OrganisationsApi = factory(root.CatalogueApi.ApiClient, root.CatalogueApi.Organisations);
  }
}(this, function(ApiClient, Organisations) {
  'use strict';

  /**
   * Organisations service.
   * @module api/OrganisationsApi
   * @version 1.0.0-private-beta
   */

  /**
   * Constructs a new OrganisationsApi. 
   * @alias module:api/OrganisationsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Retrieve an Organisation for the given Contact
     * @param {String} contactId CRM identifier of Contact
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Organisations} and HTTP response
     */
    this.apiOrganisationsByContactByContactIdGetWithHttpInfo = function(contactId) {
      var postBody = null;

      // verify the required parameter 'contactId' is set
      if (contactId === undefined || contactId === null) {
        throw new Error("Missing the required parameter 'contactId' when calling apiOrganisationsByContactByContactIdGet");
      }


      var pathParams = {
        'contactId': contactId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basic', 'oauth2'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Organisations;

      return this.apiClient.callApi(
        '/api/Organisations/ByContact/{contactId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Retrieve an Organisation for the given Contact
     * @param {String} contactId CRM identifier of Contact
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Organisations}
     */
    this.apiOrganisationsByContactByContactIdGet = function(contactId) {
      return this.apiOrganisationsByContactByContactIdGetWithHttpInfo(contactId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
