/**
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SolutionEx'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/SolutionEx'));
  } else {
    // Browser globals (root is window)
    if (!root.CatalogueApi) {
      root.CatalogueApi = {};
    }
    root.CatalogueApi.SolutionsExApi = factory(root.CatalogueApi.ApiClient, root.CatalogueApi.SolutionEx);
  }
}(this, function(ApiClient, SolutionEx) {
  'use strict';

  /**
   * SolutionsEx service.
   * @module api/SolutionsExApi
   * @version 1.0.0-private-beta
   */

  /**
   * Constructs a new SolutionsExApi. 
   * @alias module:api/SolutionsExApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Get a list of Solutions, each with a list of corresponding TechnicalContact, ClaimedCapability, ClaimedStandard et al
     * @param {String} organisationId CRM identifier of Organisation
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/SolutionEx>} and HTTP response
     */
    this.apiPorcelainSolutionsExByOrganisationByOrganisationIdGetWithHttpInfo = function(organisationId) {
      var postBody = null;

      // verify the required parameter 'organisationId' is set
      if (organisationId === undefined || organisationId === null) {
        throw new Error("Missing the required parameter 'organisationId' when calling apiPorcelainSolutionsExByOrganisationByOrganisationIdGet");
      }


      var pathParams = {
        'organisationId': organisationId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basic', 'oauth2'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [SolutionEx];

      return this.apiClient.callApi(
        '/api/porcelain/SolutionsEx/ByOrganisation/{organisationId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get a list of Solutions, each with a list of corresponding TechnicalContact, ClaimedCapability, ClaimedStandard et al
     * @param {String} organisationId CRM identifier of Organisation
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/SolutionEx>}
     */
    this.apiPorcelainSolutionsExByOrganisationByOrganisationIdGet = function(organisationId) {
      return this.apiPorcelainSolutionsExByOrganisationByOrganisationIdGetWithHttpInfo(organisationId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get a Solution with a list of corresponding TechnicalContact, ClaimedCapability, ClaimedStandard et al
     * @param {String} solutionId CRM identifier of Solution
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SolutionEx} and HTTP response
     */
    this.apiPorcelainSolutionsExBySolutionBySolutionIdGetWithHttpInfo = function(solutionId) {
      var postBody = null;

      // verify the required parameter 'solutionId' is set
      if (solutionId === undefined || solutionId === null) {
        throw new Error("Missing the required parameter 'solutionId' when calling apiPorcelainSolutionsExBySolutionBySolutionIdGet");
      }


      var pathParams = {
        'solutionId': solutionId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basic', 'oauth2'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = SolutionEx;

      return this.apiClient.callApi(
        '/api/porcelain/SolutionsEx/BySolution/{solutionId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get a Solution with a list of corresponding TechnicalContact, ClaimedCapability, ClaimedStandard et al
     * @param {String} solutionId CRM identifier of Solution
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SolutionEx}
     */
    this.apiPorcelainSolutionsExBySolutionBySolutionIdGet = function(solutionId) {
      return this.apiPorcelainSolutionsExBySolutionBySolutionIdGetWithHttpInfo(solutionId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update an existing Solution, TechnicalContact, ClaimedCapability, ClaimedStandard et al with new information
     * @param {Object} opts Optional parameters
     * @param {module:model/SolutionEx} opts.solnEx Solution, TechnicalContact, ClaimedCapability, ClaimedStandard et al with updated information
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.apiPorcelainSolutionsExUpdatePutWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = opts['solnEx'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basic', 'oauth2'];
      var contentTypes = ['application/json-patch+json', 'application/json', 'text/json', 'application/_*+json'];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/porcelain/SolutionsEx/Update', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Update an existing Solution, TechnicalContact, ClaimedCapability, ClaimedStandard et al with new information
     * @param {Object} opts Optional parameters
     * @param {module:model/SolutionEx} opts.solnEx Solution, TechnicalContact, ClaimedCapability, ClaimedStandard et al with updated information
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.apiPorcelainSolutionsExUpdatePut = function(opts) {
      return this.apiPorcelainSolutionsExUpdatePutWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
