/**
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PaginatedListStandardsApplicable', 'model/StandardsApplicable'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PaginatedListStandardsApplicable'), require('../model/StandardsApplicable'));
  } else {
    // Browser globals (root is window)
    if (!root.CatalogueApi) {
      root.CatalogueApi = {};
    }
    root.CatalogueApi.StandardsApplicableApi = factory(root.CatalogueApi.ApiClient, root.CatalogueApi.PaginatedListStandardsApplicable, root.CatalogueApi.StandardsApplicable);
  }
}(this, function(ApiClient, PaginatedListStandardsApplicable, StandardsApplicable) {
  'use strict';

  /**
   * StandardsApplicable service.
   * @module api/StandardsApplicableApi
   * @version 1.0.0-private-beta
   */

  /**
   * Constructs a new StandardsApplicableApi. 
   * @alias module:api/StandardsApplicableApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Retrieve claim, given the claim’s CRM identifier
     * @param {String} id CRM identifier of claim
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/StandardsApplicable} and HTTP response
     */
    this.apiStandardsApplicableByIdGetWithHttpInfo = function(id) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling apiStandardsApplicableByIdGet");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basic', 'oauth2'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = StandardsApplicable;

      return this.apiClient.callApi(
        '/api/StandardsApplicable/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Retrieve claim, given the claim’s CRM identifier
     * @param {String} id CRM identifier of claim
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/StandardsApplicable}
     */
    this.apiStandardsApplicableByIdGet = function(id) {
      return this.apiStandardsApplicableByIdGetWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Retrieve all claimed standards for a solution in a paged list,   given the solution’s CRM identifier
     * @param {String} solutionId CRM identifier of solution
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pageIndex 1-based index of page to return.  Defaults to 1
     * @param {Number} opts.pageSize number of items per page.  Defaults to 20
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaginatedListStandardsApplicable} and HTTP response
     */
    this.apiStandardsApplicableBySolutionBySolutionIdGetWithHttpInfo = function(solutionId, opts) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'solutionId' is set
      if (solutionId === undefined || solutionId === null) {
        throw new Error("Missing the required parameter 'solutionId' when calling apiStandardsApplicableBySolutionBySolutionIdGet");
      }


      var pathParams = {
        'solutionId': solutionId
      };
      var queryParams = {
        'pageIndex': opts['pageIndex'],
        'pageSize': opts['pageSize'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basic', 'oauth2'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = PaginatedListStandardsApplicable;

      return this.apiClient.callApi(
        '/api/StandardsApplicable/BySolution/{solutionId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Retrieve all claimed standards for a solution in a paged list,   given the solution’s CRM identifier
     * @param {String} solutionId CRM identifier of solution
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pageIndex 1-based index of page to return.  Defaults to 1
     * @param {Number} opts.pageSize number of items per page.  Defaults to 20
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaginatedListStandardsApplicable}
     */
    this.apiStandardsApplicableBySolutionBySolutionIdGet = function(solutionId, opts) {
      return this.apiStandardsApplicableBySolutionBySolutionIdGetWithHttpInfo(solutionId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete an existing claimed standard for a solution
     * @param {Object} opts Optional parameters
     * @param {module:model/StandardsApplicable} opts.claimedstandard existing claimed standard information
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.apiStandardsApplicableDeleteWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = opts['claimedstandard'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basic', 'oauth2'];
      var contentTypes = ['application/json-patch+json', 'application/json', 'text/json', 'application/_*+json'];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/StandardsApplicable', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Delete an existing claimed standard for a solution
     * @param {Object} opts Optional parameters
     * @param {module:model/StandardsApplicable} opts.claimedstandard existing claimed standard information
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.apiStandardsApplicableDelete = function(opts) {
      return this.apiStandardsApplicableDeleteWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create a new claimed standard for a solution
     * @param {Object} opts Optional parameters
     * @param {module:model/StandardsApplicable} opts.claimedstandard new claimed standard information
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/StandardsApplicable} and HTTP response
     */
    this.apiStandardsApplicablePostWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = opts['claimedstandard'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basic', 'oauth2'];
      var contentTypes = ['application/json-patch+json', 'application/json', 'text/json', 'application/_*+json'];
      var accepts = ['application/json'];
      var returnType = StandardsApplicable;

      return this.apiClient.callApi(
        '/api/StandardsApplicable', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Create a new claimed standard for a solution
     * @param {Object} opts Optional parameters
     * @param {module:model/StandardsApplicable} opts.claimedstandard new claimed standard information
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/StandardsApplicable}
     */
    this.apiStandardsApplicablePost = function(opts) {
      return this.apiStandardsApplicablePostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update an existing claimed standard with new information
     * @param {Object} opts Optional parameters
     * @param {module:model/StandardsApplicable} opts.claimedstandard claimed standard with updated information
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.apiStandardsApplicablePutWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = opts['claimedstandard'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basic', 'oauth2'];
      var contentTypes = ['application/json-patch+json', 'application/json', 'text/json', 'application/_*+json'];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/StandardsApplicable', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Update an existing claimed standard with new information
     * @param {Object} opts Optional parameters
     * @param {module:model/StandardsApplicable} opts.claimedstandard claimed standard with updated information
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.apiStandardsApplicablePut = function(opts) {
      return this.apiStandardsApplicablePutWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
