/**
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PaginatedListStandards', 'model/Standards'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PaginatedListStandards'), require('../model/Standards'));
  } else {
    // Browser globals (root is window)
    if (!root.CatalogueApi) {
      root.CatalogueApi = {};
    }
    root.CatalogueApi.StandardsApi = factory(root.CatalogueApi.ApiClient, root.CatalogueApi.PaginatedListStandards, root.CatalogueApi.Standards);
  }
}(this, function(ApiClient, PaginatedListStandards, Standards) {
  'use strict';

  /**
   * Standards service.
   * @module api/StandardsApi
   * @version 1.0.0-private-beta
   */

  /**
   * Constructs a new StandardsApi. 
   * @alias module:api/StandardsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Get existing/optional Standard/s which are in the given Capability
     * @param {String} capabilityId CRM identifier of Capability
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.isOptional true if the specified Standard is optional with the Capability
     * @param {Number} opts.pageIndex 1-based index of page to return.  Defaults to 1
     * @param {Number} opts.pageSize number of items per page.  Defaults to 20
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaginatedListStandards} and HTTP response
     */
    this.apiStandardsByCapabilityByCapabilityIdGetWithHttpInfo = function(capabilityId, opts) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'capabilityId' is set
      if (capabilityId === undefined || capabilityId === null) {
        throw new Error("Missing the required parameter 'capabilityId' when calling apiStandardsByCapabilityByCapabilityIdGet");
      }


      var pathParams = {
        'capabilityId': capabilityId
      };
      var queryParams = {
        'isOptional': opts['isOptional'],
        'pageIndex': opts['pageIndex'],
        'pageSize': opts['pageSize'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basic', 'oauth2'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = PaginatedListStandards;

      return this.apiClient.callApi(
        '/api/Standards/ByCapability/{capabilityId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get existing/optional Standard/s which are in the given Capability
     * @param {String} capabilityId CRM identifier of Capability
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.isOptional true if the specified Standard is optional with the Capability
     * @param {Number} opts.pageIndex 1-based index of page to return.  Defaults to 1
     * @param {Number} opts.pageSize number of items per page.  Defaults to 20
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaginatedListStandards}
     */
    this.apiStandardsByCapabilityByCapabilityIdGet = function(capabilityId, opts) {
      return this.apiStandardsByCapabilityByCapabilityIdGetWithHttpInfo(capabilityId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get existing Standard/s which are in the given Framework
     * @param {String} frameworkId CRM identifier of Framework
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pageIndex 1-based index of page to return.  Defaults to 1
     * @param {Number} opts.pageSize number of items per page.  Defaults to 20
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaginatedListStandards} and HTTP response
     */
    this.apiStandardsByFrameworkByFrameworkIdGetWithHttpInfo = function(frameworkId, opts) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'frameworkId' is set
      if (frameworkId === undefined || frameworkId === null) {
        throw new Error("Missing the required parameter 'frameworkId' when calling apiStandardsByFrameworkByFrameworkIdGet");
      }


      var pathParams = {
        'frameworkId': frameworkId
      };
      var queryParams = {
        'pageIndex': opts['pageIndex'],
        'pageSize': opts['pageSize'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basic', 'oauth2'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = PaginatedListStandards;

      return this.apiClient.callApi(
        '/api/Standards/ByFramework/{frameworkId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get existing Standard/s which are in the given Framework
     * @param {String} frameworkId CRM identifier of Framework
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pageIndex 1-based index of page to return.  Defaults to 1
     * @param {Number} opts.pageSize number of items per page.  Defaults to 20
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaginatedListStandards}
     */
    this.apiStandardsByFrameworkByFrameworkIdGet = function(frameworkId, opts) {
      return this.apiStandardsByFrameworkByFrameworkIdGetWithHttpInfo(frameworkId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get an existing standard given its CRM identifier  Typically used to retrieve previous version
     * @param {String} id CRM identifier of standard to find
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Standards} and HTTP response
     */
    this.apiStandardsByIdByIdGetWithHttpInfo = function(id) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling apiStandardsByIdByIdGet");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basic', 'oauth2'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Standards;

      return this.apiClient.callApi(
        '/api/Standards/ById/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get an existing standard given its CRM identifier  Typically used to retrieve previous version
     * @param {String} id CRM identifier of standard to find
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Standards}
     */
    this.apiStandardsByIdByIdGet = function(id) {
      return this.apiStandardsByIdByIdGetWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get several existing Standards given their CRM identifiers
     * @param {Object} opts Optional parameters
     * @param {Array.<module:model/String>} opts.ids Array of CRM identifiers of Standards to find
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Standards>} and HTTP response
     */
    this.apiStandardsByIdsPostWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = opts['ids'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basic', 'oauth2'];
      var contentTypes = ['application/json-patch+json', 'application/json', 'text/json', 'application/_*+json'];
      var accepts = ['application/json'];
      var returnType = [Standards];

      return this.apiClient.callApi(
        '/api/Standards/ByIds', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get several existing Standards given their CRM identifiers
     * @param {Object} opts Optional parameters
     * @param {Array.<module:model/String>} opts.ids Array of CRM identifiers of Standards to find
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Standards>}
     */
    this.apiStandardsByIdsPost = function(opts) {
      return this.apiStandardsByIdsPostWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Retrieve all current standards in a paged list
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pageIndex 1-based index of page to return.  Defaults to 1
     * @param {Number} opts.pageSize number of items per page.  Defaults to 20
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PaginatedListStandards} and HTTP response
     */
    this.apiStandardsGetWithHttpInfo = function(opts) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'pageIndex': opts['pageIndex'],
        'pageSize': opts['pageSize'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basic', 'oauth2'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = PaginatedListStandards;

      return this.apiClient.callApi(
        '/api/Standards', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Retrieve all current standards in a paged list
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pageIndex 1-based index of page to return.  Defaults to 1
     * @param {Number} opts.pageSize number of items per page.  Defaults to 20
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PaginatedListStandards}
     */
    this.apiStandardsGet = function(opts) {
      return this.apiStandardsGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
