/**
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CatalogueApi);
  }
}(this, function(expect, CatalogueApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CatalogueApi.SolutionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SolutionsApi', function() {
    describe('apiSolutionsByFrameworkByFrameworkIdGet', function() {
      it('should call apiSolutionsByFrameworkByFrameworkIdGet successfully', function(done) {
        //uncomment below and update the code to test apiSolutionsByFrameworkByFrameworkIdGet
        //instance.apiSolutionsByFrameworkByFrameworkIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiSolutionsByIdByIdGet', function() {
      it('should call apiSolutionsByIdByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiSolutionsByIdByIdGet
        //instance.apiSolutionsByIdByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiSolutionsByOrganisationByOrganisationIdGet', function() {
      it('should call apiSolutionsByOrganisationByOrganisationIdGet successfully', function(done) {
        //uncomment below and update the code to test apiSolutionsByOrganisationByOrganisationIdGet
        //instance.apiSolutionsByOrganisationByOrganisationIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiSolutionsDelete', function() {
      it('should call apiSolutionsDelete successfully', function(done) {
        //uncomment below and update the code to test apiSolutionsDelete
        //instance.apiSolutionsDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiSolutionsPost', function() {
      it('should call apiSolutionsPost successfully', function(done) {
        //uncomment below and update the code to test apiSolutionsPost
        //instance.apiSolutionsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiSolutionsPut', function() {
      it('should call apiSolutionsPut successfully', function(done) {
        //uncomment below and update the code to test apiSolutionsPut
        //instance.apiSolutionsPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
