/**
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CatalogueApi);
  }
}(this, function(expect, CatalogueApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CatalogueApi.StandardsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StandardsApi', function() {
    describe('apiStandardsByCapabilityByCapabilityIdGet', function() {
      it('should call apiStandardsByCapabilityByCapabilityIdGet successfully', function(done) {
        //uncomment below and update the code to test apiStandardsByCapabilityByCapabilityIdGet
        //instance.apiStandardsByCapabilityByCapabilityIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiStandardsByFrameworkByFrameworkIdGet', function() {
      it('should call apiStandardsByFrameworkByFrameworkIdGet successfully', function(done) {
        //uncomment below and update the code to test apiStandardsByFrameworkByFrameworkIdGet
        //instance.apiStandardsByFrameworkByFrameworkIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiStandardsByIdByIdGet', function() {
      it('should call apiStandardsByIdByIdGet successfully', function(done) {
        //uncomment below and update the code to test apiStandardsByIdByIdGet
        //instance.apiStandardsByIdByIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiStandardsByIdsPost', function() {
      it('should call apiStandardsByIdsPost successfully', function(done) {
        //uncomment below and update the code to test apiStandardsByIdsPost
        //instance.apiStandardsByIdsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiStandardsGet', function() {
      it('should call apiStandardsGet successfully', function(done) {
        //uncomment below and update the code to test apiStandardsGet
        //instance.apiStandardsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
