//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\d-jaac1\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://hscicdevr26.api.crm11.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"Gif.Plugins.PluginEntities" /out:"C:\Users\d-jaac1\AppData\Roaming\MscrmTools\XrmToolBox\Settings\plugins\CrmServiceContext.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"z-Office365.Apps@HSCIC365.onmicrosoft.com" /password:"********" 
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Gif.Plugins.PluginEntities
{
	
	/// <summary>
	/// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public partial class CrmServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CrmServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Gif.Plugins.PluginEntities.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Gif.Plugins.PluginEntities.Account> AccountSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Gif.Plugins.PluginEntities.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Gif.Plugins.PluginEntities.cc_capability"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Gif.Plugins.PluginEntities.cc_capability> cc_capabilitySet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Gif.Plugins.PluginEntities.cc_capability>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Gif.Plugins.PluginEntities.cc_capabilityimplemented"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Gif.Plugins.PluginEntities.cc_capabilityimplemented> cc_capabilityimplementedSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Gif.Plugins.PluginEntities.cc_capabilityimplemented>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Gif.Plugins.PluginEntities.cc_capabilitystandard"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Gif.Plugins.PluginEntities.cc_capabilitystandard> cc_capabilitystandardSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Gif.Plugins.PluginEntities.cc_capabilitystandard>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Gif.Plugins.PluginEntities.cc_evidence"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Gif.Plugins.PluginEntities.cc_evidence> cc_evidenceSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Gif.Plugins.PluginEntities.cc_evidence>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Gif.Plugins.PluginEntities.cc_framework"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Gif.Plugins.PluginEntities.cc_framework> cc_frameworkSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Gif.Plugins.PluginEntities.cc_framework>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Gif.Plugins.PluginEntities.cc_review"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Gif.Plugins.PluginEntities.cc_review> cc_reviewSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Gif.Plugins.PluginEntities.cc_review>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Gif.Plugins.PluginEntities.cc_solution"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Gif.Plugins.PluginEntities.cc_solution> cc_solutionSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Gif.Plugins.PluginEntities.cc_solution>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Gif.Plugins.PluginEntities.cc_solutioncapability"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Gif.Plugins.PluginEntities.cc_solutioncapability> cc_solutioncapabilitySet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Gif.Plugins.PluginEntities.cc_solutioncapability>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Gif.Plugins.PluginEntities.cc_standard"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Gif.Plugins.PluginEntities.cc_standard> cc_standardSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Gif.Plugins.PluginEntities.cc_standard>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Gif.Plugins.PluginEntities.cc_standardapplicable"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Gif.Plugins.PluginEntities.cc_standardapplicable> cc_standardapplicableSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Gif.Plugins.PluginEntities.cc_standardapplicable>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Gif.Plugins.PluginEntities.cc_technicalcontact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Gif.Plugins.PluginEntities.cc_technicalcontact> cc_technicalcontactSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Gif.Plugins.PluginEntities.cc_technicalcontact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Gif.Plugins.PluginEntities.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Gif.Plugins.PluginEntities.Contact> ContactSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Gif.Plugins.PluginEntities.Contact>();
			}
		}
	}
}