/**
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Capabilities', 'model/OptionalStandard'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Capabilities'), require('./OptionalStandard'));
  } else {
    // Browser globals (root is window)
    if (!root.CatalogueApi) {
      root.CatalogueApi = {};
    }
    root.CatalogueApi.CapabilityMapping = factory(root.CatalogueApi.ApiClient, root.CatalogueApi.Capabilities, root.CatalogueApi.OptionalStandard);
  }
}(this, function(ApiClient, Capabilities, OptionalStandard) {
  'use strict';




  /**
   * The CapabilityMapping model module.
   * @module model/CapabilityMapping
   * @version 1.0.0-private-beta
   */

  /**
   * Constructs a new <code>CapabilityMapping</code>.
   * A single Capability with its corresponding OptionalStandard
   * @alias module:model/CapabilityMapping
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>CapabilityMapping</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CapabilityMapping} obj Optional instance to populate.
   * @return {module:model/CapabilityMapping} The populated <code>CapabilityMapping</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('capability')) {
        obj['capability'] = Capabilities.constructFromObject(data['capability']);
      }
      if (data.hasOwnProperty('optionalStandard')) {
        obj['optionalStandard'] = ApiClient.convertToType(data['optionalStandard'], [OptionalStandard]);
      }
    }
    return obj;
  }

  /**
   * NHSD.GPITF.BuyingCatalog.Models.Porcelain.CapabilityMapping.Capability
   * @member {module:model/Capabilities} capability
   */
  exports.prototype['capability'] = undefined;
  /**
   * A list of OptionalStandard
   * @member {Array.<module:model/OptionalStandard>} optionalStandard
   */
  exports.prototype['optionalStandard'] = undefined;



  return exports;
}));


