/**
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CapabilityMapping', 'model/Standards'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CapabilityMapping'), require('./Standards'));
  } else {
    // Browser globals (root is window)
    if (!root.CatalogueApi) {
      root.CatalogueApi = {};
    }
    root.CatalogueApi.CapabilityMappings = factory(root.CatalogueApi.ApiClient, root.CatalogueApi.CapabilityMapping, root.CatalogueApi.Standards);
  }
}(this, function(ApiClient, CapabilityMapping, Standards) {
  'use strict';




  /**
   * The CapabilityMappings model module.
   * @module model/CapabilityMappings
   * @version 1.0.0-private-beta
   */

  /**
   * Constructs a new <code>CapabilityMappings</code>.
   * All CapabilityMapping with all corresponding Standard
   * @alias module:model/CapabilityMappings
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>CapabilityMappings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CapabilityMappings} obj Optional instance to populate.
   * @return {module:model/CapabilityMappings} The populated <code>CapabilityMappings</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('capabilityMapping')) {
        obj['capabilityMapping'] = ApiClient.convertToType(data['capabilityMapping'], [CapabilityMapping]);
      }
      if (data.hasOwnProperty('standard')) {
        obj['standard'] = ApiClient.convertToType(data['standard'], [Standards]);
      }
    }
    return obj;
  }

  /**
   * NHSD.GPITF.BuyingCatalog.Models.Porcelain.CapabilityMappings.CapabilityMapping
   * @member {Array.<module:model/CapabilityMapping>} capabilityMapping
   */
  exports.prototype['capabilityMapping'] = undefined;
  /**
   * A list of NHSD.GPITF.BuyingCatalog.Models.Porcelain.CapabilityMappings.Standard
   * @member {Array.<module:model/Standards>} standard
   */
  exports.prototype['standard'] = undefined;



  return exports;
}));


