/**
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BlobInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BlobInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.CatalogueApi) {
      root.CatalogueApi = {};
    }
    root.CatalogueApi.ClaimBlobInfoMap = factory(root.CatalogueApi.ApiClient, root.CatalogueApi.BlobInfo);
  }
}(this, function(ApiClient, BlobInfo) {
  'use strict';




  /**
   * The ClaimBlobInfoMap model module.
   * @module model/ClaimBlobInfoMap
   * @version 1.0.0-private-beta
   */

  /**
   * Constructs a new <code>ClaimBlobInfoMap</code>.
   * Mapping between a claimed capability or standard and it&#39;s corresponding  folders and files in blob datastore
   * @alias module:model/ClaimBlobInfoMap
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ClaimBlobInfoMap</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClaimBlobInfoMap} obj Optional instance to populate.
   * @return {module:model/ClaimBlobInfoMap} The populated <code>ClaimBlobInfoMap</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('claimId')) {
        obj['claimId'] = ApiClient.convertToType(data['claimId'], 'String');
      }
      if (data.hasOwnProperty('blobInfos')) {
        obj['blobInfos'] = ApiClient.convertToType(data['blobInfos'], [BlobInfo]);
      }
    }
    return obj;
  }

  /**
   * Unique identifier of claimed capability or standard
   * @member {String} claimId
   */
  exports.prototype['claimId'] = undefined;
  /**
   * List of folders and files associated with this claimed capability or standard
   * @member {Array.<module:model/BlobInfo>} blobInfos
   */
  exports.prototype['blobInfos'] = undefined;



  return exports;
}));


