/**
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EntityTagHeaderValue'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EntityTagHeaderValue'));
  } else {
    // Browser globals (root is window)
    if (!root.CatalogueApi) {
      root.CatalogueApi = {};
    }
    root.CatalogueApi.FileResult = factory(root.CatalogueApi.ApiClient, root.CatalogueApi.EntityTagHeaderValue);
  }
}(this, function(ApiClient, EntityTagHeaderValue) {
  'use strict';




  /**
   * The FileResult model module.
   * @module model/FileResult
   * @version 1.0.0-private-beta
   */

  /**
   * Constructs a new <code>FileResult</code>.
   * @alias module:model/FileResult
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>FileResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FileResult} obj Optional instance to populate.
   * @return {module:model/FileResult} The populated <code>FileResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('contentType')) {
        obj['contentType'] = ApiClient.convertToType(data['contentType'], 'String');
      }
      if (data.hasOwnProperty('fileDownloadName')) {
        obj['fileDownloadName'] = ApiClient.convertToType(data['fileDownloadName'], 'String');
      }
      if (data.hasOwnProperty('lastModified')) {
        obj['lastModified'] = ApiClient.convertToType(data['lastModified'], 'Date');
      }
      if (data.hasOwnProperty('entityTag')) {
        obj['entityTag'] = EntityTagHeaderValue.constructFromObject(data['entityTag']);
      }
    }
    return obj;
  }

  /**
   * @member {String} contentType
   */
  exports.prototype['contentType'] = undefined;
  /**
   * @member {String} fileDownloadName
   */
  exports.prototype['fileDownloadName'] = undefined;
  /**
   * @member {Date} lastModified
   */
  exports.prototype['lastModified'] = undefined;
  /**
   * @member {module:model/EntityTagHeaderValue} entityTag
   */
  exports.prototype['entityTag'] = undefined;



  return exports;
}));


