/**
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CatalogueApi) {
      root.CatalogueApi = {};
    }
    root.CatalogueApi.Solutions = factory(root.CatalogueApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Solutions model module.
   * @module model/Solutions
   * @version 1.0.0-private-beta
   */

  /**
   * Constructs a new <code>Solutions</code>.
   * A product and/or service provided by an ‘organisation’.  Note that a ‘solution’ has a link to zero or one previous ‘solution’  Generally, only interested in current ‘solution’  Standard MS Dynamics CRM entity
   * @alias module:model/Solutions
   * @class
   * @param id {String} Unique identifier of entity
   * @param organisationId {String} Unique identifier of organisation
   * @param createdById {String} Unique identifier of Contact who created this entity  Derived from calling context  SET ON SERVER
   * @param modifiedById {String} Unique identifier of Contact who last modified this entity  Derived from calling context  SET ON SERVER
   */
  var exports = function(id, organisationId, createdById, modifiedById) {
    var _this = this;

    _this['id'] = id;

    _this['organisationId'] = organisationId;


    _this['createdById'] = createdById;

    _this['modifiedById'] = modifiedById;




  };

  /**
   * Constructs a <code>Solutions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Solutions} obj Optional instance to populate.
   * @return {module:model/Solutions} The populated <code>Solutions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('previousId')) {
        obj['previousId'] = ApiClient.convertToType(data['previousId'], 'String');
      }
      if (data.hasOwnProperty('organisationId')) {
        obj['organisationId'] = ApiClient.convertToType(data['organisationId'], 'String');
      }
      if (data.hasOwnProperty('version')) {
        obj['version'] = ApiClient.convertToType(data['version'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('createdById')) {
        obj['createdById'] = ApiClient.convertToType(data['createdById'], 'String');
      }
      if (data.hasOwnProperty('createdOn')) {
        obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'Date');
      }
      if (data.hasOwnProperty('modifiedById')) {
        obj['modifiedById'] = ApiClient.convertToType(data['modifiedById'], 'String');
      }
      if (data.hasOwnProperty('modifiedOn')) {
        obj['modifiedOn'] = ApiClient.convertToType(data['modifiedOn'], 'Date');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('productPage')) {
        obj['productPage'] = ApiClient.convertToType(data['productPage'], 'String');
      }
    }
    return obj;
  }

  /**
   * Unique identifier of entity
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Unique identifier of previous version of entity
   * @member {String} previousId
   */
  exports.prototype['previousId'] = undefined;
  /**
   * Unique identifier of organisation
   * @member {String} organisationId
   */
  exports.prototype['organisationId'] = undefined;
  /**
   * Version of solution
   * @member {String} version
   */
  exports.prototype['version'] = undefined;
  /**
   * Current status of this solution
   * @member {module:model/Solutions.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * Unique identifier of Contact who created this entity  Derived from calling context  SET ON SERVER
   * @member {String} createdById
   */
  exports.prototype['createdById'] = undefined;
  /**
   * UTC date and time at which record created  Set by server when creating record  SET ON SERVER
   * @member {Date} createdOn
   */
  exports.prototype['createdOn'] = undefined;
  /**
   * Unique identifier of Contact who last modified this entity  Derived from calling context  SET ON SERVER
   * @member {String} modifiedById
   */
  exports.prototype['modifiedById'] = undefined;
  /**
   * UTC date and time at which record last modified  Set by server when creating record  SET ON SERVER
   * @member {Date} modifiedOn
   */
  exports.prototype['modifiedOn'] = undefined;
  /**
   * Name of solution, as displayed to a user
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Description of solution, as displayed to a user
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * Serialised product page
   * @member {String} productPage
   */
  exports.prototype['productPage'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "Failed"
     * @const
     */
    "Failed": "Failed",
    /**
     * value: "Draft"
     * @const
     */
    "Draft": "Draft",
    /**
     * value: "Registered"
     * @const
     */
    "Registered": "Registered",
    /**
     * value: "CapabilitiesAssessment"
     * @const
     */
    "CapabilitiesAssessment": "CapabilitiesAssessment",
    /**
     * value: "StandardsCompliance"
     * @const
     */
    "StandardsCompliance": "StandardsCompliance",
    /**
     * value: "FinalApproval"
     * @const
     */
    "FinalApproval": "FinalApproval",
    /**
     * value: "SolutionPage"
     * @const
     */
    "SolutionPage": "SolutionPage",
    /**
     * value: "Approved"
     * @const
     */
    "Approved": "Approved"  };


  return exports;
}));


