/**
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CatalogueApi) {
      root.CatalogueApi = {};
    }
    root.CatalogueApi.Standards = factory(root.CatalogueApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Standards model module.
   * @module model/Standards
   * @version 1.0.0-private-beta
   */

  /**
   * Constructs a new <code>Standards</code>.
   * A formal set of requirements eg  * ISO 9001  Note that a ‘standard’ has a link to zero or one previous ‘standard’  Generally, only interested in current ‘standard’
   * @alias module:model/Standards
   * @class
   * @param id {String} Unique identifier of entity
   */
  var exports = function(id) {
    var _this = this;


    _this['id'] = id;





  };

  /**
   * Constructs a <code>Standards</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Standards} obj Optional instance to populate.
   * @return {module:model/Standards} The populated <code>Standards</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('isOverarching')) {
        obj['isOverarching'] = ApiClient.convertToType(data['isOverarching'], 'Boolean');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('previousId')) {
        obj['previousId'] = ApiClient.convertToType(data['previousId'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
    }
    return obj;
  }

  /**
   * True if this standard applies to all solutions
   * @member {Boolean} isOverarching
   */
  exports.prototype['isOverarching'] = undefined;
  /**
   * Unique identifier of entity
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Unique identifier of previous version of entity
   * @member {String} previousId
   */
  exports.prototype['previousId'] = undefined;
  /**
   * Name of Capability/Standard, as displayed to a user
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Description of Capability/Standard, as displayed to a user
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * URL with further information
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * Category of Capability/Standard
   * @member {String} type
   */
  exports.prototype['type'] = undefined;



  return exports;
}));


